# Generated by Django 2.0.4 on 2018-04-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateStudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=126)),
                ('Email', models.EmailField(max_length=254)),
                ('Branch', models.CharField(max_length=126)),
                ('Year', models.IntegerField(default=0)),
                ('placementValue', models.CharField(default='none', max_length=126)),
            ],
        ),
    ]
