# Generated by Django 2.0.4 on 2018-04-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createstudentmodel',
            name='placementValue',
            field=models.CharField(default='none', max_length=126, null=True),
        ),
    ]
